[package]
name = "hw01_my_hw"
version = "0.1.0"
authors = ["fjordyo <fjordyo0707@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
